chore: Added custom container image of pgsql16(rhel9) including pg_cron and modified development environment with scheduled tasks in pg_cron. Performance improvements in DB schema too
Signed-off-by: Alejandro Villegas <alex.ansi.c@gmail.com>

diff --git a/deployments/compose/compose-integration-tests.yaml b/deployments/compose/compose-integration-tests.yaml
--- a/deployments/compose/compose-integration-tests.yaml
+++ b/deployments/compose/compose-integration-tests.yaml
@@ -28,6 +28,8 @@ services:
       POSTGRESQL_PASSWORD: "password"
       POSTGRESQL_DATABASE: "clusteriq"
       POSTGRESQL_ADMIN_PASSWORD: "admin"
+      POSTGRESQL_LIBRARIES: "pg_cron"
+      POSTGRESQL_EXTENSIONS: "pg_cron"
     networks:
       - cluster_iq_test
 
@@ -37,17 +39,23 @@ services:
     restart: "no"
     command: |
       sh -c '
-        while true; do
-          psql postgresql://user:password@pgsql-test:5432/clusteriq -c "SELECT true" && break || sleep 2;
-        done
-        psql postgresql://user:password@pgsql-test:5432/clusteriq < /init.sql && { echo "Ok"; } || { echo "Initialization Failed"; exit 1; }
+         echo "Waiting for PGSQL to start up"
+         while true; do
+             psql postgresql://user:password@pgsql:5432/clusteriq -c "SELECT true" && break || sleep 2;
+         done
 
-        if [[ "$CIQ_DB_PRELOAD_DATA" -eq "true" ]]; then
-          echo "Initializing DB with fake data"
-          psql postgresql://user:password@pgsql-test:5432/clusteriq < /integration_tests_data.sql && { echo "Ok"; } || { echo "Initialization Failed"; exit 1; }
-        fi
+         echo "Initializing ClusterIQ Database"
+         psql postgresql://user:password@pgsql:5432/clusteriq < /init.sql && { echo "Ok"; } || { echo "Initialization Failed"; exit 1; }
 
-        echo "Done!"
+         echo "Creating PG_CRON tasks"
+         psql postgresql://postgres:admin@pgsql:5432/postgres < /cron.sql && { echo "Ok"; } || { echo "Cron Tasks creation Failed"; exit 1; }
+
+         if [[ "$CIQ_DB_PRELOAD_DATA" -eq "true" ]]; then
+           echo "Initializing DB with fake data"
+           psql postgresql://user:password@pgsql-test:5432/clusteriq < /integration_tests_data.sql && { echo "Ok"; } || { echo "Initialization Failed"; exit 1; }
+         fi
+
+         echo "Done!"
       '
     environment:
       CIQ_DB_PRELOAD_DATA: "true"
